### ISSUE TITLE
好奇你们的服务器是放在哪儿的

### ISSUE THREAD

**Issue by christolan** [zjuchenyuan/cc98tech#4]
看你们没有用GitHub pages，好奇你们服务器是放在哪儿的，理论上可以外网看98了吗？

**Comment by zjuchenyuan** [comment]
这个项目是传统的cs架构，严重依赖后端的redis缓存和mysql数据库，现在加上了elasticsearch搜索，所以无法使用github pages这种纯静态服务

任何不关机的电脑都可以当服务器，我觉得实现基础的功能一个树莓派就行吧hhh

外网访问98为啥不手机上戳rvpn.zju.edu.cn呢，现在已经实现了快速登录（rvpn网页版在登录rvpn后访问cc98.tech登录时选择记住我，下次再打开将跳过cc98登录过程直接完成登录）

**Comment by christolan** [comment]
> 这个项目是传统的cs架构，严重依赖后端的redis缓存和mysql数据库，现在加上了elasticsearch搜索，所以无法使用github pages这种纯静态服务
> 
> 任何不关机的电脑都可以当服务器，我觉得实现基础的功能一个树莓派就行吧hhh
> 
> 外网访问98为啥不手机上戳rvpn.zju.edu.cn呢，现在已经实现了快速登录（rvpn网页版在登录rvpn后访问cc98.tech登录时选择记住我，下次再打开将跳过cc98登录过程直接完成登录）

随便找个电脑当服务器的问题应该是ip吧。
我看过了我自己电脑的ip是222开头，ping了一下cc98.tech的ip是10开头，我自己的电脑如果当服务器的话应该只有跟我一个网段的人才能访问吧，不是很懂学校的网络结构，不知道你们是怎么解决的？

**Comment by zjuchenyuan** [comment]
你想多了hhh 内网的ip是均能访问的 你配个静态路由不就有10.的ip了嘛
似乎222.205是整个教育网都能访问的公网ip，只是禁止了特定端口
