### ISSUE TITLE
通过RVPN网页版访问时在私信页面查看用户详情的BUG

### ISSUE THREAD

**Issue by CoolSpring8** [zjuchenyuan/cc98tech#7]
![snipaste_2019-02-19_12-08-34](https://user-images.githubusercontent.com/8985327/52989659-68f54800-343f-11e9-9c95-69a5162abf4b.png)
![snipaste_2019-02-19_12-10-14](https://user-images.githubusercontent.com/8985327/52989660-698dde80-343f-11e9-818f-967518717c7b.png)
如图（加了马赛克有点惨不忍睹），这个地方本来应该可以点进用户详情页，但在RVPN网页版的环境下对URL的replace似乎没有生效。

以及建议在这个页面上可以在用户头像上也加上用户详情页的链接，个人觉得点头像的操作更符合直觉一些。

**Comment by zjuchenyuan** [comment]
fixed, thanks
