### ISSUE TITLE
某些用户的“用户详情-创建的更多主题”页面上部分帖子最后回复日期显示不正确

### ISSUE THREAD

**Issue by CoolSpring8** [zjuchenyuan/cc98tech#8]
在形如 https://www.cc98.tech/user/id/123456/topics 的页面上可能会出现最后回复日期显示早于发帖日期的情况，但并不是每个人的页面上都会这样。
![image](https://user-images.githubusercontent.com/8985327/53695960-f9973500-3dfc-11e9-96b7-b7d26b89ead2.png)
![image](https://user-images.githubusercontent.com/8985327/53695995-74f8e680-3dfd-11e9-9c1a-55170e33c579.png)
两张示例图中的UID分别是351515和600588（我不知道把这个暴露在这里会不会有影响，如果有的话我会编辑掉）。

**Comment by zjuchenyuan** [comment]
恭喜你发现98的一处设计问题：锁沉帖子实际上就是修改帖子的最后回复时间

因为版面的帖子列表就是按最后回复时间排序的，通过锁沉操作修改这个值来达到沉帖效果

这个问题无法修复 官方数据就这样

**Comment by CoolSpring8** [comment]
原来这个就是“锁定并下沉1000天”的效果啊……感谢
