### ISSUE TITLE
RVPN网页版点击标题得到的预览中的链接存在错误

### ISSUE THREAD

**Issue by CoolSpring8** [zjuchenyuan/cc98tech#9]
和 #7 类似，RVPN网页版环境下，在首页或其他主题列表页，点击帖子标题空白区域得到的预览中，类似于红框所示的链接存在错误：
![Snipaste_2019-05-10_21-32-14](https://user-images.githubusercontent.com/8985327/57531250-929d7b80-736b-11e9-9a74-f1f2cc9f313d.png)

![image](https://user-images.githubusercontent.com/8985327/57531311-b660c180-736b-11e9-82fc-f939995a88ef.png)

**Comment by CoolSpring8** [comment]
看到已经修了，辛苦了，感谢

**Comment by zjuchenyuan** [comment]
这个bug出现的原因是使用json批量获取onmousevoer来提高用户体验，但rvpn服务器不会替换json内容
目前在rvpn上禁用了这个feature，只有在用户点击后才会加载 直接返回html能被rvpn服务器正常替换

**Comment by CoolSpring8** [comment]
又发现了一个：点击"用户添加的帖子标签"时也是如此（指区别于论坛官方的“出”“yq”“有偿实验”等tag）

这个大概是加个"ROOT"或者"window.ROOT"就能解决？不过这种坑是还会有很多吗……
